import { useEffect, useMemo, useState } from 'react';
import { QueryClient, QueryClientProvider, useQueryClient } from '@tanstack/react-query';
import { Link, Route, Switch, useLocation } from 'wouter';
import {
  Activity, ArrowRight, Bell, CalendarDays, Check, CheckCircle2,
  CircleAlert, Clock3, Download, FileText, HeartHandshake, Home, LogOut,
  MapPin, Plus, Search, ShieldCheck, Star, UserRound, UsersRound, X,
} from 'lucide-react';
import {
  getDownloadRequestsBackupQueryKey, getGetCurrentUserQueryKey, getGetDashboardQueryKey, getListRequestsQueryKey,
  getListSeniorsQueryKey, getListWorkersQueryKey, useAssignRequest, useCreateRequest,
  useCreateReview, useCreateSenior, useCreateWorker, useDownloadRequestsBackup,
  useGetCurrentUser, useGetDashboard, useListRequests, useListSeniors, useListServices,
  useListWorkers, useLogin, useRegisterClient, useUpdateRequestStatus, setAuthTokenGetter,
  type RequestInputServiceType, type ServiceRequest, type User,
} from '@workspace/api-client-react';
import { ErrorBoundary } from '@/components/error-boundary';
import { Toaster } from '@/components/ui/toaster';
import { TooltipProvider } from '@/components/ui/tooltip';
import NotFound from '@/pages/not-found';

const queryClient = new QueryClient();
const serviceTypes: { value: RequestInputServiceType; label: string; description: string }[] = [
  { value: 'CITA_MEDICA', label: 'Cita médica', description: 'Acompañamiento y traslado a una consulta.' },
  { value: 'TRAMITE', label: 'Trámite', description: 'Ayuda presencial con gestiones importantes.' },
  { value: 'COMPRAS', label: 'Compras', description: 'Compras esenciales para el hogar.' },
  { value: 'TECNOLOGIA', label: 'Tecnología', description: 'Apoyo para resolver dudas digitales.' },
  { value: 'RECREACION', label: 'Recreación', description: 'Una salida, paseo o compañía.' },
];
const roleLabel: Record<string, string> = {
  CLIENTE_DECISOR: 'Familia',
  PERSONAL_ACOMPANANTE: 'Acompañante',
  ADMINISTRADOR: 'Administración',
};
const statusLabel: Record<string, string> = {
  SOLICITADO: 'Solicitado', ASIGNADO: 'Asignado', EN_CURSO: 'En curso',
  FINALIZADO: 'Finalizado', CANCELADO: 'Cancelado',
};
const errorText = (error: unknown, fallback = 'No pudimos completar la acción. Intenta nuevamente.') =>
  error instanceof Error ? error.message.replace(/^HTTP \d+ [^:]+:\s*/, '') : fallback;
const initials = (name = '') => name.split(' ').map((part) => part[0]).slice(0, 2).join('').toUpperCase() || 'CO';
const formatDate = (date?: string) => date ? new Date(date).toLocaleDateString('es-CL', { day: '2-digit', month: 'short' }) : '—';
const formatDateTime = (date?: string) => date ? new Date(date).toLocaleString('es-CL', { day: '2-digit', month: 'short', hour: '2-digit', minute: '2-digit' }) : '—';

function Logo({ compact = false }: { compact?: boolean }) {
  return <div className="flex items-center gap-3">
    <div className="flex h-10 w-10 items-center justify-center rounded-[13px] bg-[hsl(var(--primary))] text-[hsl(var(--primary-foreground))] shadow-[0_4px_0_hsl(13_52%_38%)]"><HeartHandshake size={21} strokeWidth={2.3} /></div>
    {!compact && <div><div className="font-display text-[1.4rem] font-bold tracking-[-.04em]">contigo</div><div className="text-[.61rem] font-bold uppercase tracking-[.18em] opacity-60">acompañamiento</div></div>}
  </div>;
}

function Sidebar({ user }: { user: User }) {
  const [location, setLocation] = useLocation();
  const admin = user.role === 'ADMINISTRADOR';
  const links = [
    { href: '/', label: 'Resumen', icon: Home },
    ...(admin ? [
      { href: '/solicitudes', label: 'Solicitudes', icon: FileText },
      { href: '/trabajadores', label: 'Trabajadores', icon: UsersRound },
    ] : [
      { href: '/solicitar', label: 'Pedir acompañamiento', icon: Plus },
      { href: '/mis-servicios', label: 'Mis servicios', icon: Activity },
    ]),
  ];
  const logout = () => { localStorage.removeItem('contigo_token'); queryClient.clear(); setLocation('/login'); };
  return <aside className="sidebar flex min-h-[100dvh] flex-col p-5">
    <Link href="/" data-testid="link-sidebar-home" className="mb-12"><Logo /></Link>
    <div className="mb-3 px-3 text-[.64rem] font-bold uppercase tracking-[.16em] opacity-45">Espacio de trabajo</div>
    <nav className="space-y-1">
      {links.map(({ href, label, icon: Icon }) => <Link key={href} href={href} data-testid={`link-nav-${label.toLowerCase().replaceAll(' ', '-')}`} className={`flex items-center gap-3 rounded-xl px-3 py-3 text-[.82rem] font-semibold transition ${location === href ? 'bg-[hsl(var(--sidebar-primary))] text-[hsl(var(--sidebar-primary-foreground))]' : 'text-[hsl(var(--sidebar-foreground)/.72)] hover:bg-[hsl(var(--sidebar-accent))] hover:text-[hsl(var(--sidebar-foreground))]'}`}><Icon size={17} /><span>{label}</span>{href === '/solicitudes' && <span className="ml-auto rounded-full bg-[hsl(var(--accent))] px-2 py-0.5 text-[.6rem] text-[hsl(var(--foreground))]">8</span>}</Link>)}
    </nav>
    <div className="mt-auto">
      <div className="mb-3 rounded-2xl border border-[hsl(var(--sidebar-border))] bg-[hsl(var(--sidebar-accent))] p-3">
        <div className="mb-3 flex items-center gap-3"><Avatar name={user.fullName} dark /><div className="min-w-0"><div className="truncate text-[.8rem] font-bold">{user.fullName}</div><div className="truncate text-[.68rem] opacity-55">{roleLabel[user.role]}</div></div></div>
        <button onClick={logout} data-testid="button-logout" className="flex w-full items-center gap-2 rounded-lg px-1 py-1 text-left text-[.72rem] font-semibold opacity-65 transition hover:opacity-100"><LogOut size={14} /> Cerrar sesión</button>
      </div>
      <div className="px-3 text-[.68rem] leading-relaxed opacity-45">Tu información se maneja con cuidado.<br />Contigo, paso a paso.</div>
    </div>
  </aside>;
}

function MobileNav({ user }: { user: User }) {
  const [location] = useLocation();
  const links = user.role === 'ADMINISTRADOR' ? [{ href: '/', label: 'Resumen' }, { href: '/solicitudes', label: 'Solicitudes' }, { href: '/trabajadores', label: 'Trabajadores' }] : [{ href: '/', label: 'Resumen' }, { href: '/solicitar', label: 'Pedir ayuda' }, { href: '/mis-servicios', label: 'Mis servicios' }];
  return <><div className="mobile-bar"><Logo compact /><div className="flex items-center gap-2 text-[.7rem] font-semibold opacity-70"><Avatar name={user.fullName} dark size="sm" /> {roleLabel[user.role]}</div></div><nav className="mobile-nav">{links.map((link) => <Link key={link.href} href={link.href} className={location === link.href ? 'active' : ''} data-testid={`link-mobile-${link.label.toLowerCase().replaceAll(' ', '-')}`}>{link.label}</Link>)}</nav></>;
}

function Avatar({ name, dark = false, size = 'md' }: { name?: string; dark?: boolean; size?: 'sm' | 'md' }) {
  return <div data-testid={`avatar-${initials(name)}`} className={`${size === 'sm' ? 'h-7 w-7 text-[.6rem]' : 'h-9 w-9 text-[.72rem]'} flex shrink-0 items-center justify-center rounded-xl font-bold ${dark ? 'bg-[hsl(var(--accent))] text-[hsl(var(--foreground))]' : 'bg-[hsl(var(--muted))] text-[hsl(var(--secondary))]'}`}>{initials(name)}</div>;
}

function LoadingState({ rows = 3 }: { rows?: number }) {
  return <div className="space-y-3" data-testid="loading-state">{Array.from({ length: rows }).map((_, i) => <div key={i} className="surface flex items-center gap-4 p-4"><div className="skeleton h-10 w-10" /><div className="flex-1 space-y-2"><div className="skeleton h-3 w-1/3" /><div className="skeleton h-3 w-2/3" /></div></div>)}</div>;
}
function EmptyState({ icon: Icon = FileText, title, body, action }: { icon?: typeof FileText; title: string; body: string; action?: React.ReactNode }) {
  return <div className="surface flex min-h-[220px] flex-col items-center justify-center p-8 text-center" data-testid="empty-state"><div className="mb-4 flex h-12 w-12 items-center justify-center rounded-2xl bg-[hsl(var(--muted))] text-[hsl(var(--secondary))]"><Icon size={21} /></div><h3 className="font-display text-lg font-bold">{title}</h3><p className="mt-1 max-w-sm text-sm text-[hsl(var(--muted-foreground))]">{body}</p>{action && <div className="mt-5">{action}</div>}</div>;
}
function ErrorState({ message, retry }: { message: string; retry: () => void }) {
  return <div className="surface flex items-center gap-3 border-[hsl(var(--destructive)/.25)] p-4 text-sm" data-testid="error-state"><CircleAlert className="text-[hsl(var(--destructive))]" size={19} /><div className="flex-1"><strong className="block">Algo no salió bien</strong><span className="text-[hsl(var(--muted-foreground))]">{message}</span></div><button className="btn btn-secondary" onClick={retry} data-testid="button-retry">Reintentar</button></div>;
}

function AppShell({ user, children }: { user: User; children: React.ReactNode }) {
  return <div className="app-shell app-noise"><Sidebar user={user} /><main className="main-area"><MobileNav user={user} />{children}</main></div>;
}

function AuthLayout({ children, register = false }: { children: React.ReactNode; register?: boolean }) {
  return <div className="app-noise flex min-h-[100dvh] bg-[hsl(var(--background))]">
    <div className="hidden w-[43%] flex-col justify-between overflow-hidden bg-[hsl(var(--sidebar))] p-10 text-[hsl(var(--sidebar-foreground))] lg:flex">
      <Logo />
      <div className="relative max-w-md"><div className="absolute -left-16 -top-20 h-56 w-56 rounded-full bg-[hsl(var(--primary)/.2)] blur-2xl" /><div className="relative"><div className="mb-5 flex items-center gap-2 text-[.7rem] font-bold uppercase tracking-[.16em] text-[hsl(var(--accent))]"><ShieldCheck size={15} /> Confianza para cada familia</div><h1 className="font-display text-5xl font-bold leading-[.98] tracking-[-.05em]">Ayudar también es estar cerca.</h1><p className="mt-6 max-w-sm text-[1rem] leading-relaxed opacity-65">Coordinamos acompañamiento confiable para que tu familia pueda vivir con más calma.</p></div></div>
      <div className="flex items-center gap-3 text-[.71rem] opacity-45"><HeartHandshake size={17} /> Presencia que se organiza con cuidado</div>
    </div>
    <div className="flex flex-1 items-center justify-center p-5 sm:p-10"><div className="w-full max-w-[440px]"><div className="mb-10 lg:hidden"><Logo /></div>{children}</div></div>
  </div>;
}

function LoginPage() {
  const [, setLocation] = useLocation();
  const login = useLogin();
  const [form, setForm] = useState({ email: '', password: '' });
  const [error, setError] = useState('');
  const submit = (e: React.FormEvent) => { e.preventDefault(); setError(''); login.mutate({ data: form }, { onSuccess: (session) => { localStorage.setItem('contigo_token', session.token); queryClient.setQueryData(getGetCurrentUserQueryKey(), session.user); setLocation('/'); }, onError: (err) => setError(errorText(err, 'Correo o contraseña incorrectos. Revisa tus datos e intenta nuevamente.')) }); };
  return <AuthLayout><div className="mb-8"><div className="eyebrow mb-3">Bienvenido de vuelta</div><h1 className="font-display text-4xl font-bold tracking-[-.045em]">Entrar a Contigo</h1><p className="mt-3 text-sm leading-relaxed text-[hsl(var(--muted-foreground))]">Coordina ayuda para quienes más quieres.</p></div>
    {error && <div className="mb-5 flex gap-2 rounded-xl border border-[hsl(var(--destructive)/.25)] bg-[hsl(var(--destructive)/.07)] p-3 text-sm text-[hsl(var(--destructive))]" data-testid="error-login"><CircleAlert size={17} className="mt-0.5 shrink-0" />{error}</div>}
    <form onSubmit={submit} className="space-y-4"><label><span className="field-label">Correo electrónico</span><input required type="email" className="field" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} placeholder="tu@correo.com" data-testid="input-login-email" /></label><label><span className="field-label">Contraseña</span><input required minLength={6} type="password" className="field" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} placeholder="Mínimo 6 caracteres" data-testid="input-login-password" /></label><button disabled={login.isPending} className="btn btn-primary mt-3 w-full py-3.5" data-testid="button-login">{login.isPending ? 'Ingresando…' : 'Ingresar a mi espacio'}<ArrowRight size={16} /></button></form>
    <p className="mt-7 text-center text-sm text-[hsl(var(--muted-foreground))]">¿Aún no tienes cuenta? <Link href="/registro" data-testid="link-register" className="font-bold text-[hsl(var(--primary))]">Crear cuenta familiar</Link></p>
  </AuthLayout>;
}

function RegisterPage() {
  const [, setLocation] = useLocation();
  const register = useRegisterClient();
  const [form, setForm] = useState({ fullName: '', email: '', phone: '', dni: '', password: '' });
  const [error, setError] = useState('');
  const submit = (e: React.FormEvent) => { e.preventDefault(); setError(''); register.mutate({ data: { ...form, phone: form.phone || null, dni: form.dni || null } }, { onSuccess: (session) => { localStorage.setItem('contigo_token', session.token); queryClient.setQueryData(getGetCurrentUserQueryKey(), session.user); setLocation('/'); }, onError: (err) => setError(errorText(err)) }); };
  return <AuthLayout register><div className="mb-7"><div className="eyebrow mb-3">Un comienzo tranquilo</div><h1 className="font-display text-4xl font-bold tracking-[-.045em]">Crea tu cuenta</h1><p className="mt-3 text-sm leading-relaxed text-[hsl(var(--muted-foreground))]">Regístrate como cliente y empieza a organizar acompañamiento.</p></div>
    {error && <div className="mb-4 rounded-xl bg-[hsl(var(--destructive)/.08)] p-3 text-sm text-[hsl(var(--destructive))]" data-testid="error-register">{error}</div>}
    <form onSubmit={submit} className="grid gap-3 sm:grid-cols-2"><label className="sm:col-span-2"><span className="field-label">Nombre completo</span><input required minLength={2} className="field" value={form.fullName} onChange={(e) => setForm({ ...form, fullName: e.target.value })} placeholder="Ej. Paula González" data-testid="input-register-name" /></label><label><span className="field-label">Correo electrónico</span><input required type="email" className="field" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} placeholder="tu@correo.com" data-testid="input-register-email" /></label><label><span className="field-label">Teléfono</span><input className="field" value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} placeholder="+56 9..." data-testid="input-register-phone" /></label><label><span className="field-label">RUT / DNI <span className="font-normal opacity-55">(opcional)</span></span><input className="field" value={form.dni} onChange={(e) => setForm({ ...form, dni: e.target.value })} placeholder="12345678" data-testid="input-register-dni" /></label><label><span className="field-label">Contraseña</span><input required minLength={6} type="password" className="field" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} placeholder="Mínimo 6 caracteres" data-testid="input-register-password" /></label><button disabled={register.isPending} className="btn btn-primary mt-3 sm:col-span-2 py-3.5" data-testid="button-register">{register.isPending ? 'Creando cuenta…' : 'Crear mi cuenta'}<ArrowRight size={16} /></button></form>
    <p className="mt-6 text-center text-sm text-[hsl(var(--muted-foreground))]">¿Ya tienes una cuenta? <Link href="/login" data-testid="link-login" className="font-bold text-[hsl(var(--primary))]">Volver a ingresar</Link></p>
  </AuthLayout>;
}

function PageHeader({ eyebrow, title, body, action }: { eyebrow: string; title: string; body?: string; action?: React.ReactNode }) {
  return <header className="mb-8 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><div className="eyebrow mb-2">{eyebrow}</div><h1 className="section-title">{title}</h1>{body && <p className="mt-2 max-w-2xl text-sm text-[hsl(var(--muted-foreground))]">{body}</p>}</div>{action}</header>;
}
function StatCard({ icon: Icon, label, value, note, accent = false }: { icon: typeof Activity; label: string; value: string | number; note: string; accent?: boolean }) {
  return <div className={`surface relative overflow-hidden p-5 ${accent ? 'bg-[hsl(var(--sidebar))] text-[hsl(var(--sidebar-foreground))] border-transparent' : ''}`}><div className={`mb-6 flex h-9 w-9 items-center justify-center rounded-xl ${accent ? 'bg-[hsl(var(--primary))] text-[hsl(var(--primary-foreground))]' : 'bg-[hsl(var(--muted))] text-[hsl(var(--secondary))]'}`}><Icon size={17} /></div><div className="text-[.68rem] font-bold uppercase tracking-[.12em] opacity-60">{label}</div><div className="mt-1 font-display text-3xl font-bold tracking-[-.04em]">{value}</div><div className="mt-1 text-xs opacity-60">{note}</div>{accent && <div className="absolute -right-5 -top-6 h-28 w-28 rounded-full border-[16px] border-[hsl(var(--accent)/.25)]" />}</div>;
}

function DashboardPage({ user }: { user: User }) {
  const dashboard = useGetDashboard({ query: { queryKey: getGetDashboardQueryKey() } });
  const requests = dashboard.data?.recentRequests ?? [];
  const stats = dashboard.data?.stats;
  return <div className="page-wrap fade-up"><PageHeader eyebrow={`Buenos días, ${user.fullName.split(' ')[0]}`} title={user.role === 'ADMINISTRADOR' ? 'Todo bajo control.' : 'Tu red de cuidado'} body={user.role === 'ADMINISTRADOR' ? 'Una vista clara para que cada solicitud encuentre a la persona adecuada.' : 'Lo importante, en un mismo lugar. Estamos contigo en cada paso.'} action={user.role === 'CLIENTE_DECISOR' ? <Link href="/solicitar" className="btn btn-primary" data-testid="button-dashboard-request"><Plus size={16} /> Nueva solicitud</Link> : undefined} />
    {dashboard.isLoading ? <LoadingState rows={3} /> : dashboard.isError ? <ErrorState message={errorText(dashboard.error)} retry={() => dashboard.refetch()} /> : <>
      <div className="mb-8 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><StatCard icon={FileText} label="Solicitudes totales" value={stats?.totalRequests ?? 0} note="Historial de tu espacio" accent /><StatCard icon={Clock3} label="Pendientes" value={stats?.pendingRequests ?? 0} note="Esperando coordinación" /><StatCard icon={Activity} label="Servicios activos" value={stats?.activeServices ?? 0} note="Acompañamientos en marcha" /><StatCard icon={Star} label="Valoración media" value={stats?.averageRating ? `${stats.averageRating.toFixed(1)}/5` : '—'} note="Experiencia de las familias" /></div>
      <div className="grid gap-5 lg:grid-cols-[1.35fr_.65fr]"><section className="surface overflow-hidden"><div className="flex items-center justify-between border-b p-5"><div><h2 className="font-display text-xl font-bold">Actividad reciente</h2><p className="mt-1 text-xs text-[hsl(var(--muted-foreground))]">Últimas solicitudes en tu espacio</p></div><Link href="/mis-servicios" className="text-xs font-bold text-[hsl(var(--primary))]" data-testid="link-dashboard-services">Ver todas</Link></div>{requests.length ? <div className="divide-y">{requests.slice(0, 5).map((request) => <RequestRow key={request.id} request={request} />)}</div> : <div className="p-6"><EmptyState icon={HeartHandshake} title="Aún no hay actividad" body="Cuando solicites un servicio, aparecerá aquí." action={user.role === 'CLIENTE_DECISOR' ? <Link className="btn btn-primary" href="/solicitar" data-testid="button-empty-request">Pedir acompañamiento</Link> : undefined} /></div>}</section><aside className="surface bg-[hsl(var(--secondary))] p-6 text-[hsl(var(--secondary-foreground))]"><div className="mb-8 flex items-center justify-between"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[hsl(var(--accent))] text-[hsl(var(--foreground))]"><Bell size={18} /></div><span className="text-[.65rem] font-bold uppercase tracking-[.12em] opacity-55">A tener en cuenta</span></div><h2 className="font-display text-2xl font-bold leading-tight">La tranquilidad también se coordina.</h2><p className="mt-3 text-sm leading-relaxed opacity-70">Mantén los datos de tus adultos mayores actualizados para que cada acompañamiento sea más seguro.</p>{user.role === 'CLIENTE_DECISOR' && <Link href="/solicitar" className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-[hsl(var(--accent))]" data-testid="link-dashboard-tip">Ir a mis solicitudes <ArrowRight size={15} /></Link>}</aside></div>
    </>}</div>;
}

function RequestRow({ request, admin = false }: { request: ServiceRequest; admin?: boolean }) {
  return <div className="flex flex-col gap-3 px-5 py-4 sm:flex-row sm:items-center sm:justify-between" data-testid={`row-request-${request.id}`}><div className="flex min-w-0 items-center gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-[hsl(var(--muted))] text-[hsl(var(--secondary))]"><CalendarDays size={17} /></div><div className="min-w-0"><div className="truncate text-sm font-bold">{request.serviceLabel}</div><div className="mt-0.5 truncate text-xs text-[hsl(var(--muted-foreground))]">{admin ? `${request.clientName} · ` : ''}{request.seniorName} · {formatDateTime(request.scheduledAt)}</div></div></div><div className="flex items-center gap-3 pl-[52px] sm:pl-0"><span className={`status-pill status-${request.status}`}>{statusLabel[request.status] ?? request.status}</span>{admin && <span className="hidden text-xs text-[hsl(var(--muted-foreground))] lg:inline">{request.workerName ?? 'Sin asignar'}</span>}</div></div>;
}

function SeniorForm({ onCreated }: { onCreated: () => void }) {
  const qc = useQueryClient(); const create = useCreateSenior();
  const [form, setForm] = useState({ fullName: '', age: '', medicalNotes: '', emergencyContact: '' }); const [error, setError] = useState('');
  const submit = (e: React.FormEvent) => { e.preventDefault(); setError(''); create.mutate({ data: { fullName: form.fullName, age: Number(form.age), medicalNotes: form.medicalNotes || null, emergencyContact: form.emergencyContact || null } }, { onSuccess: () => { qc.invalidateQueries({ queryKey: getListSeniorsQueryKey() }); setForm({ fullName: '', age: '', medicalNotes: '', emergencyContact: '' }); onCreated(); }, onError: (err) => setError(errorText(err)) }); };
  return <form onSubmit={submit} className="space-y-3"><div className="grid gap-3 sm:grid-cols-[1fr_130px]"><label><span className="field-label">Nombre completo</span><input required minLength={2} className="field" value={form.fullName} onChange={(e) => setForm({ ...form, fullName: e.target.value })} placeholder="Ej. Elena Morales" data-testid="input-senior-name" /></label><label><span className="field-label">Edad</span><input required min={60} max={130} type="number" className="field" value={form.age} onChange={(e) => setForm({ ...form, age: e.target.value })} placeholder="75" data-testid="input-senior-age" /></label></div><label><span className="field-label">Notas médicas <span className="font-normal opacity-55">(opcional)</span></span><textarea className="field min-h-20 resize-y" value={form.medicalNotes} onChange={(e) => setForm({ ...form, medicalNotes: e.target.value })} placeholder="Información que debamos considerar…" data-testid="input-senior-notes" /></label><label><span className="field-label">Contacto de emergencia <span className="font-normal opacity-55">(opcional)</span></span><input className="field" value={form.emergencyContact} onChange={(e) => setForm({ ...form, emergencyContact: e.target.value })} placeholder="Nombre y teléfono" data-testid="input-senior-emergency" /></label>{error && <p className="text-sm text-[hsl(var(--destructive))]" data-testid="error-senior">{error}</p>}<button className="btn btn-primary w-full" disabled={create.isPending} data-testid="button-create-senior">{create.isPending ? 'Guardando…' : 'Guardar adulto mayor'}<Check size={16} /></button></form>;
}

function RequestPage() {
  const qc = useQueryClient(); const [, setLocation] = useLocation();
  const seniors = useListSeniors(); const services = useListServices(); const create = useCreateRequest();
  const [form, setForm] = useState({ seniorId: '', serviceType: '' as RequestInputServiceType | '', scheduledAt: '', durationHours: '2', pickupAddress: '', destinationAddress: '', notes: '' }); const [showSenior, setShowSenior] = useState(false); const [error, setError] = useState('');
  const options = services.data?.length
    ? services.data.map((service) => ({ id: service.id, label: service.label, description: service.description }))
    : serviceTypes.map((service) => ({ id: service.value, label: service.label, description: service.description }));
  useEffect(() => { if (!form.seniorId && seniors.data?.[0]) setForm((current) => ({ ...current, seniorId: seniors.data![0].id })); }, [seniors.data, form.seniorId]);
  useEffect(() => { if (!form.serviceType && options[0]) setForm((current) => ({ ...current, serviceType: options[0].id as RequestInputServiceType })); }, [options, form.serviceType]);
  const submit = (e: React.FormEvent) => { e.preventDefault(); setError(''); create.mutate({ data: { seniorId: form.seniorId, serviceType: form.serviceType as RequestInputServiceType, scheduledAt: new Date(form.scheduledAt).toISOString(), durationHours: Number(form.durationHours), pickupAddress: form.pickupAddress, destinationAddress: form.destinationAddress || null, notes: form.notes || null } }, { onSuccess: () => { qc.invalidateQueries({ queryKey: getListRequestsQueryKey() }); qc.invalidateQueries({ queryKey: getGetDashboardQueryKey() }); setLocation('/mis-servicios'); }, onError: (err) => setError(errorText(err)) }); };
  return <div className="page-wrap fade-up"><PageHeader eyebrow="Nuevo acompañamiento" title="Pedir ayuda, sin vueltas." body="Cuéntanos lo esencial y nos ocuparemos de coordinar una persona adecuada." />
    {seniors.isLoading || services.isLoading ? <LoadingState rows={4} /> : seniors.isError || services.isError ? <ErrorState message="No pudimos cargar las opciones disponibles." retry={() => { seniors.refetch(); services.refetch(); }} /> : <div className="grid gap-5 lg:grid-cols-[1fr_340px]"><form onSubmit={submit} className="surface space-y-5 p-5 sm:p-7"><div><div className="mb-3 flex items-center justify-between"><h2 className="font-display text-xl font-bold">¿Para quién es?</h2><button type="button" onClick={() => setShowSenior(!showSenior)} className="btn btn-ghost px-2 text-xs" data-testid="button-toggle-senior"><Plus size={14} /> Agregar adulto mayor</button></div>{seniors.data?.length ? <div className="grid gap-2 sm:grid-cols-2">{seniors.data.map((senior) => <button type="button" key={senior.id} onClick={() => setForm({ ...form, seniorId: senior.id })} className={`rounded-xl border p-3 text-left transition ${form.seniorId === senior.id ? 'border-[hsl(var(--primary))] bg-[hsl(var(--primary)/.07)]' : 'hover:border-[hsl(var(--primary)/.45)]'}`} data-testid={`button-senior-${senior.id}`}><div className="flex items-center gap-3"><Avatar name={senior.fullName} /><div><div className="text-sm font-bold">{senior.fullName}</div><div className="text-xs text-[hsl(var(--muted-foreground))]">{senior.age} años</div></div>{form.seniorId === senior.id && <CheckCircle2 className="ml-auto text-[hsl(var(--primary))]" size={17} />}</div></button>)}</div> : <EmptyState icon={UserRound} title="Agrega a tu primer adulto mayor" body="Así podremos personalizar cada acompañamiento." />}{showSenior && <div className="mt-4 rounded-2xl bg-[hsl(var(--muted)/.55)] p-4"><SeniorForm onCreated={() => setShowSenior(false)} /></div>}</div>
      <div><h2 className="mb-3 font-display text-xl font-bold">¿Qué necesitan?</h2><div className="grid gap-2 sm:grid-cols-2">{options.map((service) => <button type="button" key={service.id} onClick={() => setForm({ ...form, serviceType: service.id as RequestInputServiceType })} className={`rounded-xl border p-3 text-left transition ${form.serviceType === service.id ? 'border-[hsl(var(--primary))] bg-[hsl(var(--primary)/.07)]' : 'hover:border-[hsl(var(--primary)/.45)]'}`} data-testid={`button-service-${service.id}`}><div className="flex items-center justify-between"><span className="text-sm font-bold">{service.label}</span>{form.serviceType === service.id && <CheckCircle2 size={17} className="text-[hsl(var(--primary))]" />}</div><span className="mt-1 block text-xs leading-relaxed text-[hsl(var(--muted-foreground))]">{service.description}</span></button>)}</div></div>
      <div className="grid gap-4 sm:grid-cols-2"><label><span className="field-label">Fecha y hora</span><input required type="datetime-local" className="field" value={form.scheduledAt} onChange={(e) => setForm({ ...form, scheduledAt: e.target.value })} data-testid="input-request-date" /></label><label><span className="field-label">Duración (horas)</span><input required min=".5" max="24" step=".5" type="number" className="field" value={form.durationHours} onChange={(e) => setForm({ ...form, durationHours: e.target.value })} data-testid="input-request-duration" /></label></div>
      <div className="grid gap-4 sm:grid-cols-2"><label><span className="field-label">Punto de encuentro</span><div className="relative"><MapPin size={15} className="absolute left-3 top-3.5 text-[hsl(var(--muted-foreground))]" /><input required minLength={3} className="field pl-9" value={form.pickupAddress} onChange={(e) => setForm({ ...form, pickupAddress: e.target.value })} placeholder="Dirección de origen" data-testid="input-request-pickup" /></div></label><label><span className="field-label">Destino <span className="font-normal opacity-55">(opcional)</span></span><input className="field" value={form.destinationAddress} onChange={(e) => setForm({ ...form, destinationAddress: e.target.value })} placeholder="Clínica, oficina…" data-testid="input-request-destination" /></label></div>
      <label><span className="field-label">Algo más que debamos saber <span className="font-normal opacity-55">(opcional)</span></span><textarea className="field min-h-20 resize-y" value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} placeholder="Preferencias, indicaciones o detalles…" data-testid="input-request-notes" /></label>{error && <div className="rounded-xl bg-[hsl(var(--destructive)/.08)] p-3 text-sm text-[hsl(var(--destructive))]" data-testid="error-request">{error}</div>}<div className="flex flex-col-reverse gap-2 border-t pt-5 sm:flex-row sm:justify-end"><Link href="/mis-servicios" className="btn btn-secondary" data-testid="button-cancel-request">Cancelar</Link><button disabled={create.isPending || !form.seniorId} className="btn btn-primary" data-testid="button-submit-request">{create.isPending ? 'Enviando…' : 'Enviar solicitud'}<ArrowRight size={16} /></button></div></form>
      <aside className="h-fit rounded-[18px] bg-[hsl(var(--secondary))] p-6 text-[hsl(var(--secondary-foreground))]"><ShieldCheck className="mb-5 text-[hsl(var(--accent))]" size={25} /><h3 className="font-display text-xl font-bold">Tu tranquilidad primero</h3><p className="mt-3 text-sm leading-relaxed opacity-70">Revisaremos los detalles y te avisaremos cuando tu solicitud tenga un acompañante asignado.</p><div className="mt-6 space-y-3 border-t border-[hsl(var(--secondary-foreground)/.15)] pt-5 text-xs opacity-65"><div className="flex gap-2"><Check size={15} /> Personas verificadas</div><div className="flex gap-2"><Check size={15} /> Seguimiento en cada etapa</div><div className="flex gap-2"><Check size={15} /> Soporte humano</div></div></aside></div>}</div>;
}

function ServicesPage({ user }: { user: User }) {
  const requests = useListRequests(); const review = useCreateReview(); const qc = useQueryClient();
  const [reviewing, setReviewing] = useState<ServiceRequest | null>(null); const [rating, setRating] = useState(5); const [comment, setComment] = useState('');
  const submitReview = (e: React.FormEvent) => { e.preventDefault(); if (!reviewing) return; review.mutate({ data: { requestId: reviewing.id, rating, comment: comment || null } }, { onSuccess: () => { qc.invalidateQueries({ queryKey: getListRequestsQueryKey() }); qc.invalidateQueries({ queryKey: getGetDashboardQueryKey() }); setReviewing(null); } }); };
  return <div className="page-wrap fade-up"><PageHeader eyebrow={user.role === 'PERSONAL_ACOMPANANTE' ? 'Tu agenda' : 'Historial familiar'} title={user.role === 'PERSONAL_ACOMPANANTE' ? 'Servicios asignados' : 'Mis servicios'} body="Sigue cada acompañamiento y revisa su avance en un vistazo." action={user.role === 'CLIENTE_DECISOR' ? <Link href="/solicitar" className="btn btn-primary" data-testid="button-services-request"><Plus size={16} /> Nueva solicitud</Link> : undefined} />
    {requests.isLoading ? <LoadingState rows={4} /> : requests.isError ? <ErrorState message={errorText(requests.error)} retry={() => requests.refetch()} /> : !requests.data?.length ? <EmptyState icon={HeartHandshake} title="Todavía no hay servicios" body={user.role === 'CLIENTE_DECISOR' ? 'Tu primer pedido de acompañamiento aparecerá aquí.' : 'Cuando tengas un servicio asignado, lo verás aquí.'} action={user.role === 'CLIENTE_DECISOR' ? <Link className="btn btn-primary" href="/solicitar" data-testid="button-services-empty-request">Pedir acompañamiento</Link> : undefined} /> : <div className="space-y-3">{requests.data.map((request) => <div key={request.id} className="surface p-5" data-testid={`card-service-${request.id}`}><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div className="flex items-start gap-3"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-[hsl(var(--muted))] text-[hsl(var(--secondary))]"><CalendarDays size={19} /></div><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-display text-lg font-bold">{request.serviceLabel}</h3><span className={`status-pill status-${request.status}`}>{statusLabel[request.status] ?? request.status}</span></div><p className="mt-1 text-xs text-[hsl(var(--muted-foreground))]">{request.seniorName} · {formatDateTime(request.scheduledAt)} · {request.durationHours} h</p></div></div><div className="flex items-center gap-4 pl-14 md:pl-0"><div className="text-right"><div className="text-xs text-[hsl(var(--muted-foreground))]">Acompañante</div><div className="text-sm font-bold">{request.workerName ?? 'Buscando persona'}</div></div>{request.status === 'FINALIZADO' && !request.rating && user.role === 'CLIENTE_DECISOR' && <button onClick={() => setReviewing(request)} className="btn btn-secondary" data-testid={`button-review-${request.id}`}><Star size={15} /> Valorar</button>}</div></div><div className="mt-4 flex flex-wrap gap-x-5 gap-y-2 border-t pt-4 text-xs text-[hsl(var(--muted-foreground))]"><span className="flex items-center gap-1.5"><MapPin size={13} /> {request.pickupAddress}{request.destinationAddress ? ` → ${request.destinationAddress}` : ''}</span>{request.createdAt && <span>Solicitado el {formatDate(request.createdAt)}</span>}{request.rating && <span className="flex items-center gap-1 text-[hsl(var(--secondary))]"><Star size={13} fill="currentColor" /> {request.rating}/5 {request.reviewComment ? `· ${request.reviewComment}` : ''}</span>}</div></div>)}</div>}
    {reviewing && <div className="fixed inset-0 z-30 flex items-center justify-center bg-[hsl(var(--foreground)/.35)] p-5" onMouseDown={(e) => e.target === e.currentTarget && setReviewing(null)}><form onSubmit={submitReview} className="surface w-full max-w-md p-6"><div className="mb-5 flex items-start justify-between"><div><div className="eyebrow mb-1">Tu experiencia</div><h2 className="font-display text-2xl font-bold">¿Cómo estuvo?</h2></div><button type="button" className="btn btn-ghost p-2" onClick={() => setReviewing(null)} data-testid="button-close-review"><X size={18} /></button></div><div className="mb-5 flex justify-center gap-2">{[1, 2, 3, 4, 5].map((star) => <button type="button" key={star} onClick={() => setRating(star)} className={`p-1 ${star <= rating ? 'text-[hsl(var(--accent))]' : 'text-[hsl(var(--muted))]'}`} data-testid={`button-rating-${star}`}><Star size={30} fill="currentColor" /></button>)}</div><textarea className="field min-h-24" value={comment} onChange={(e) => setComment(e.target.value)} placeholder="¿Quieres contarnos algo más?" data-testid="input-review-comment" /><button disabled={review.isPending} className="btn btn-primary mt-4 w-full" data-testid="button-submit-review">{review.isPending ? 'Guardando…' : 'Guardar valoración'}<Check size={16} /></button></form></div>}</div>;
}

function WorkersPage() {
  const workers = useListWorkers(); const create = useCreateWorker(); const qc = useQueryClient(); const [showForm, setShowForm] = useState(false); const [error, setError] = useState('');
  const [form, setForm] = useState({ fullName: '', email: '', phone: '', dni: '', password: '', skills: '', backgroundChecked: false });
  const submit = (e: React.FormEvent) => { e.preventDefault(); setError(''); create.mutate({ data: { ...form, skills: form.skills || null } }, { onSuccess: () => { qc.invalidateQueries({ queryKey: getListWorkersQueryKey() }); setShowForm(false); setForm({ fullName: '', email: '', phone: '', dni: '', password: '', skills: '', backgroundChecked: false }); }, onError: (err) => setError(errorText(err)) }); };
  return <div className="page-wrap fade-up"><PageHeader eyebrow="Equipo de acompañamiento" title="Personas que hacen la diferencia." body="Gestiona disponibilidad, habilidades y experiencia de tu equipo." action={<button className="btn btn-primary" onClick={() => setShowForm(true)} data-testid="button-new-worker"><Plus size={16} /> Registrar trabajador</button>} />
    {workers.isLoading ? <LoadingState rows={4} /> : workers.isError ? <ErrorState message={errorText(workers.error)} retry={() => workers.refetch()} /> : !workers.data?.length ? <EmptyState icon={UsersRound} title="Aún no hay trabajadores" body="Registra a la primera persona de tu equipo para comenzar." action={<button className="btn btn-primary" onClick={() => setShowForm(true)} data-testid="button-empty-worker">Registrar trabajador</button>} /> : <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{workers.data.map((worker) => <div className="surface p-5 transition hover:-translate-y-0.5" key={worker.id} data-testid={`card-worker-${worker.id}`}><div className="mb-5 flex items-start justify-between"><div className="flex items-center gap-3"><Avatar name={worker.fullName} /><div><h3 className="text-sm font-bold">{worker.fullName}</h3><p className="text-xs text-[hsl(var(--muted-foreground))]">{worker.email}</p></div></div><span className={`status-pill ${worker.status === 'DISPONIBLE' ? 'status-FINALIZADO' : worker.status === 'EN_SERVICIO' ? 'status-ASIGNADO' : 'status-CANCELADO'}`}>{worker.status === 'DISPONIBLE' ? 'Disponible' : worker.status === 'EN_SERVICIO' ? 'En servicio' : 'Inactivo'}</span></div><div className="mb-4 flex items-center gap-4 border-y py-3 text-xs"><span className="flex items-center gap-1.5"><Star size={14} className="text-[hsl(var(--accent))]" fill="currentColor" /> {worker.rating?.toFixed(1) ?? '—'}</span><span className="text-[hsl(var(--muted-foreground))]">{worker.completedServices ?? 0} servicios</span>{worker.backgroundChecked && <span className="ml-auto flex items-center gap-1 text-[hsl(var(--secondary))]"><ShieldCheck size={14} /> Verificado</span>}</div><p className="text-xs leading-relaxed text-[hsl(var(--muted-foreground))]">{worker.skills || 'Habilidades por completar'}</p></div>)}</div>}
    {showForm && <div className="fixed inset-0 z-30 flex items-center justify-center bg-[hsl(var(--foreground)/.35)] p-5" onMouseDown={(e) => e.target === e.currentTarget && setShowForm(false)}><form onSubmit={submit} className="surface max-h-[90dvh] w-full max-w-lg overflow-y-auto p-6"><div className="mb-5 flex items-start justify-between"><div><div className="eyebrow mb-1">Nuevo perfil</div><h2 className="font-display text-2xl font-bold">Registrar trabajador</h2></div><button type="button" className="btn btn-ghost p-2" onClick={() => setShowForm(false)} data-testid="button-close-worker"><X size={18} /></button></div><div className="grid gap-3 sm:grid-cols-2"><label className="sm:col-span-2"><span className="field-label">Nombre completo</span><input required minLength={2} className="field" value={form.fullName} onChange={(e) => setForm({ ...form, fullName: e.target.value })} data-testid="input-worker-name" /></label><label><span className="field-label">Correo</span><input required type="email" className="field" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} data-testid="input-worker-email" /></label><label><span className="field-label">Teléfono</span><input required className="field" value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} data-testid="input-worker-phone" /></label><label><span className="field-label">DNI</span><input required className="field" value={form.dni} onChange={(e) => setForm({ ...form, dni: e.target.value })} data-testid="input-worker-dni" /></label><label><span className="field-label">Contraseña inicial</span><input required minLength={6} type="password" className="field" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} data-testid="input-worker-password" /></label><label className="sm:col-span-2"><span className="field-label">Habilidades</span><textarea className="field min-h-20" value={form.skills} onChange={(e) => setForm({ ...form, skills: e.target.value })} placeholder="Ej. Traslados, primeros auxilios…" data-testid="input-worker-skills" /></label><label className="flex items-center gap-2 text-sm sm:col-span-2"><input type="checkbox" checked={form.backgroundChecked} onChange={(e) => setForm({ ...form, backgroundChecked: e.target.checked })} data-testid="input-worker-verified" /> Antecedentes verificados</label></div>{error && <p className="mt-3 text-sm text-[hsl(var(--destructive))]" data-testid="error-worker">{error}</p>}<button disabled={create.isPending} className="btn btn-primary mt-5 w-full" data-testid="button-submit-worker">{create.isPending ? 'Guardando…' : 'Guardar trabajador'}<Check size={16} /></button></form></div>}</div>;
}

function RequestsPage() {
  const requests = useListRequests(); const workers = useListWorkers(); const qc = useQueryClient(); const update = useUpdateRequestStatus(); const assign = useAssignRequest(); const backup = useDownloadRequestsBackup({ query: { enabled: false, queryKey: getDownloadRequestsBackupQueryKey() } });
  const [filter, setFilter] = useState('TODAS'); const [search, setSearch] = useState('');
  const filtered = useMemo(() => (requests.data ?? []).filter((r) => (filter === 'TODAS' || r.status === filter) && `${r.clientName} ${r.seniorName} ${r.serviceLabel}`.toLowerCase().includes(search.toLowerCase())), [requests.data, filter, search]);
  const refresh = () => { qc.invalidateQueries({ queryKey: getListRequestsQueryKey() }); qc.invalidateQueries({ queryKey: getGetDashboardQueryKey() }); };
  const changeStatus = (id: string, status: string) => update.mutate({ requestId: id, data: { status: status as 'SOLICITADO' } }, { onSuccess: refresh });
  const assignWorker = (id: string, workerId: string) => assign.mutate({ requestId: id, data: { workerId } }, { onSuccess: refresh });
  const download = async () => { const result = await backup.refetch(); if (result.data instanceof Blob) { const url = URL.createObjectURL(result.data); const a = document.createElement('a'); a.href = url; a.download = 'contigo-solicitudes.xlsx'; a.click(); URL.revokeObjectURL(url); } };
  return <div className="page-wrap fade-up"><PageHeader eyebrow="Centro de coordinación" title="Solicitudes en movimiento." body="Asigna, actualiza y acompaña cada caso con una vista completa." action={<button className="btn btn-secondary" onClick={download} disabled={backup.isFetching} data-testid="button-download-backup"><Download size={16} /> {backup.isFetching ? 'Preparando…' : 'Descargar respaldo'}</button>} />
    {requests.isLoading || workers.isLoading ? <LoadingState rows={5} /> : requests.isError ? <ErrorState message={errorText(requests.error)} retry={() => requests.refetch()} /> : <><div className="mb-5 flex flex-col gap-3 sm:flex-row"><div className="relative flex-1"><Search size={16} className="absolute left-3 top-3.5 text-[hsl(var(--muted-foreground))]" /><input className="field pl-9" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Buscar por familia, adulto mayor o servicio" data-testid="input-search-requests" /></div><select className="field sm:w-44" value={filter} onChange={(e) => setFilter(e.target.value)} data-testid="select-request-filter"><option value="TODAS">Todos los estados</option>{Object.entries(statusLabel).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div>{filtered.length ? <div className="surface overflow-hidden"><div className="hidden grid-cols-[1.3fr_1fr_1fr_1fr] gap-4 border-b bg-[hsl(var(--muted)/.45)] px-5 py-3 text-[.66rem] font-bold uppercase tracking-[.12em] text-[hsl(var(--muted-foreground))] md:grid"><span>Solicitud</span><span>Fecha</span><span>Acompañante</span><span>Estado</span></div><div className="divide-y">{filtered.map((request) => <div key={request.id} className="grid gap-3 px-5 py-4 md:grid-cols-[1.3fr_1fr_1fr_1fr] md:items-center md:gap-4" data-testid={`row-admin-request-${request.id}`}><div><div className="flex items-center gap-2 text-sm font-bold"><span className="truncate">{request.serviceLabel}</span><span className="rounded bg-[hsl(var(--muted))] px-1.5 py-0.5 text-[.62rem] font-medium">#{request.id.slice(-5)}</span></div><div className="mt-1 text-xs text-[hsl(var(--muted-foreground))]">{request.clientName} · {request.seniorName}</div></div><div className="text-xs text-[hsl(var(--muted-foreground))]"><span className="md:hidden">Fecha: </span>{formatDateTime(request.scheduledAt)}</div><select className="field py-2 text-xs" value={request.workerId ?? ''} onChange={(e) => e.target.value && assignWorker(request.id, e.target.value)} data-testid={`select-worker-${request.id}`}><option value="">Sin asignar</option>{workers.data?.map((worker) => <option key={worker.id} value={worker.id}>{worker.fullName}</option>)}</select><select className={`field py-2 text-xs ${`status-${request.status}`}`} value={request.status} onChange={(e) => changeStatus(request.id, e.target.value)} data-testid={`select-status-${request.id}`}>{Object.entries(statusLabel).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div>)}</div></div> : <EmptyState icon={FileText} title="No encontramos solicitudes" body={search ? 'Prueba con otro nombre o limpia la búsqueda.' : 'Las nuevas solicitudes aparecerán aquí.'} />}</>}</div>;
}

function ProtectedRouter({ user }: { user: User }) {
  return <AppShell user={user}><Switch><Route path="/" component={() => <DashboardPage user={user} />} /><Route path="/solicitar" component={RequestPage} /><Route path="/mis-servicios" component={() => <ServicesPage user={user} />} /><Route path="/trabajadores" component={WorkersPage} /><Route path="/solicitudes" component={RequestsPage} /><Route component={NotFound} /></Switch></AppShell>;
}

function Router() {
  const token = typeof window !== 'undefined' ? localStorage.getItem('contigo_token') : null;
  const me = useGetCurrentUser({ query: { enabled: !!token, queryKey: getGetCurrentUserQueryKey() } });
  if (!token) return <Switch><Route path="/registro" component={RegisterPage} /><Route path="/login" component={LoginPage} /><Route component={LoginPage} /></Switch>;
  if (me.isLoading) return <div className="flex min-h-[100dvh] items-center justify-center bg-[hsl(var(--background))]"><div className="w-64 space-y-3"><div className="skeleton h-10 w-10 rounded-xl" /><div className="skeleton h-8 w-3/4" /><div className="skeleton h-4 w-full" /></div></div>;
  if (me.isError || !me.data) { localStorage.removeItem('contigo_token'); return <LoginPage />; }
  return <ProtectedRouter user={me.data} />;
}

function App() {
  useEffect(() => { setAuthTokenGetter(() => localStorage.getItem('contigo_token')); }, []);
  return <QueryClientProvider client={queryClient}><TooltipProvider><Router /><Toaster /></TooltipProvider></QueryClientProvider>;
}

export default App;